sonar.projectKey=StefanoGaspardone_LetsTable
sonar.organization=stefanogaspardone

sonar.sources=backend/src/main/kotlin,frontend-mobile
sonar.tests=backend/src/test/kotlin,frontend-mobile/tests

sonar.test.inclusions=frontend/**/*.test.ts,frontend/**/*.test.tsx,frontend/**/*.spec.ts,frontend/**/*.spec.tsx

sonar.exclusions=**/build/**,**/node_modules/**,**/.expo/**,**/coverage/**

sonar.coverage.jacoco.xmlReportPaths=backend/build/reports/jacoco/test/jacocoTestReport.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info