sonar.projectKey=StefanoGaspardone_LetsTable
sonar.organization=stefanogaspardone

sonar.sources=backend/src/main,frontend-mobile

sonar.exclusions=**/node_modules/**,**/build/**,**/coverage/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts

sonar.java.binaries=backend/build/classes
sonar.coverage.jacoco.xmlReportPaths=backend/build/reports/jacoco/test/jacocoTestReport.xml

sonar.javascript.lcov.reportPaths=frontend-mobile/coverage/lcov.info

sonar.coverage.exclusions=\
  frontend-mobile/app/**,\
  frontend-mobile/components/**,\
  frontend-mobile/test/**,\
  frontend-mobile/types/**,\
  frontend-mobile/**/*.d.ts,\
  frontend-mobile/*.config.js,\
  frontend-mobile/*.config.ts,\
  frontend-mobile/babel.config.js,\
  frontend-mobile/jest.setup.js,\
  backend/src/main/kotlin/com/backend/**/configs/**,\
  backend/src/main/kotlin/com/backend/**/models/**,\
  backend/src/main/kotlin/com/backend/**/repositories/**,\
  backend/src/main/kotlin/com/backend/**/seeders/**,\
  backend/src/main/kotlin/com/backend/**/mappers/**,\
  backend/src/main/kotlin/com/backend/**/exceptions/**,\
  backend/src/main/kotlin/com/backend/**/security/**,\
  backend/src/main/kotlin/com/backend/**/properties/**,\
  backend/src/main/kotlin/com/backend/*Application*

  sonar.plsql.file.suffixes=-